Now azk uses an internal dns server to resolve the domain: azk.dev

diff --git a/bin/azk b/bin/azk
--- a/bin/azk
+++ b/bin/azk
@@ -2,7 +2,7 @@
 
 set -e
 
-__FILE__="${0}"
+__FILE__="$BASH_SOURCE"
 export AZK_ROOT_PATH=`cd \`dirname $(readlink ${__FILE__} || echo ${__FILE__} )\`/..; pwd`
 export AZK_DATA_PATH=${AZK_DATA_PATH:-$AZK_ROOT_PATH/data}
 
@@ -38,9 +38,6 @@ case `uname -s` in
     exit 1;
 esac
 
-# Share system
-export AZK_PING_PATH=${AZK_PING_PATH:-`which ping`}
-
 export PATH=/usr/bin:/bin:/usr/sbin
 export PATH=$AZK_ROOT_PATH/bin:$PATH
 export PATH=$AZK_ROOT_PATH/node_modules/.bin:$PATH
@@ -54,10 +51,11 @@ export NODE_PATH=$AZK_ROOT_PATH/node_modules:$NODE_PATH
 export NODE_PATH=$AZK_ROOT_PATH/lib:$NODE_PATH
 
 agent_ip() {
-  $AZK_PING_PATH -q -c 1 -t 1 $1 2>/dev/null | grep PING | sed -e "s/).*//" | sed -e "s/.*(//"
+  cat /etc/resolver/$AZK_BALANCER_HOST 2>/dev/null | awk '{ print $2 }'
 }
 
 # Configure NVM and VM
+export AZK_BALANCER_HOST="${AZK_BALANCER_HOST:-azk.dev}"
 export NVM_DIR=$AZK_DATA_PATH/nvm
 export VM_DISK_PATH=$AZK_DATA_PATH/vm
 export AZK_AGENT_VM_NAME="${AZK_AGENT_VM_NAME:-azk-agent}"
@@ -162,7 +160,7 @@ cmd_exists() {
     exit 1
   fi
 }
-cmd_exists git nc curl grep head tr
+cmd_exists git nc curl grep head tr bash
 
 # Roles
 check_data_folders() {
@@ -246,13 +244,18 @@ check_install() {
   fi
 }
 
+check_agent_is_running() {
+  cd "$AZK_ROOT_PATH"
+  ./bin/azk agent status &>/dev/null && {
+    log "$azk_fail: agent is running, stop before update or re-configure!"
+    exit 1;
+  } || return 0;
+}
+
 update_code_base() {
   if [ -n "$update" ]; then
     cd "$AZK_ROOT_PATH"
-    ./bin/azk agent status &>/dev/null && {
-      log "$azk_fail: agent is running, stop before update!"
-      exit 1;
-    }
+    check_agent_is_running
     log -n "$azk_ok: Update code..."
     git pull . origin/stable 2>&1 | logger -t azk
     log "[%{green}ok%{reset}]" >&2
@@ -283,19 +286,25 @@ vm_ip_msg() {
 }
 
 configure_vm_ip() {
-  default_ip="192.168.50.4"
+  [ "$1" != "retry" ] && check_agent_is_running
+
+  default_ip="${AZK_AGENT_VM_IP:-192.168.50.4}"
   msg="$(azk.escape "Enter de vm ip: (default: %{yellow}${default_ip}%{reset}): ")"
   read -p "$msg" ip
+
   ip=${ip:-$default_ip}
-  if azk.valid_ip "$ip"; then
-    azk.escape "Adding %{yellow}${ip}%{reset} to /etc/hosts ...";
+  if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
+    file=/etc/resolver/$AZK_BALANCER_HOST
+    azk.escape "Adding %{yellow}${ip}%{reset} to $file ...";
     set -x
-    echo -e "\n# Azk agent vm ip\n$ip azk-agent" | sudo tee -a /etc/hosts >/dev/null
+    sudo mkdir -p /etc/resolver 2>/dev/null
+    echo "nameserver $ip" | sudo tee $file
+    sudo chown $(id -u):$(id -g) $file
     set +x
     echo ""
   else
     azk.escape "$azk_fail: %{yellow}${ip}%{reset} is a invalid v4 ip, try again.";
-    configure_vm_ip;
+    configure_vm_ip retry;
   fi
 }
 
@@ -303,7 +312,11 @@ install() {
   log_i() { azk.escape -n "%{green}azk%{reset}: ${@}"; }
 
   check_install "check_unfsd" "dependencies" || msg_depens 'unfsd' "$UNFSD_INSTALL"
-  check_install "check_vm_ip" "vm ip" $1 || { vm_ip_msg; configure_vm_ip; }
+
+  # Not configure or force configure
+  [[ "${@}" =~ --configure-ip ]] && { configure_vm_ip; } || {
+    check_install "check_vm_ip" "vm ip" $1 || { vm_ip_msg; configure_vm_ip; }
+  }
 
   # Update azk code base
   [ "$1" == '--update' ] && {
@@ -365,7 +378,7 @@ azk_main() {
       install --update
       ;;
     check-install|configure)
-      install $1
+      install "${@}"
       ;;
     nvm)
       check_depedencies
